local LSM = LibStub('LibSharedMedia-3.0')

LSM:Register('statusbar', 'Asphyxia', [[Interface\AddOns\DSM\Media\StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Bezo', [[Interface\AddOns\DSM\Media\StatusBars\Bezo]])
LSM:Register('statusbar', 'Dajova', [[Interface\AddOns\DSM\Media\StatusBars\Dajova]])
LSM:Register('statusbar', 'Duffed', [[Interface\AddOns\DSM\Media\StatusBars\Duffed]])
LSM:Register('statusbar', 'Flatt', [[Interface\AddOns\DSM\Media\StatusBars\Flatt]])
LSM:Register('statusbar', 'Sinaris', [[Interface\AddOns\DSM\Media\StatusBars\Sinaris]])
LSM:Register('statusbar', 'Slate', [[Interface\AddOns\DSM\Media\StatusBars\Slate]])
LSM:Register('statusbar', 'Smooth', [[Interface\AddOns\DSM\Media\StatusBars\Smooth]])
LSM:Register('statusbar', 'Tukui', [[Interface\AddOns\DSM\Media\StatusBars\Tukui]])

LSM:Register('statusbar', 'Aluminium Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Aluminium]])
LSM:Register('statusbar', 'Asphyxia Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Asphyxia]])
LSM:Register('statusbar', 'BantoBar Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\BantoBar]])
LSM:Register('statusbar', 'Button Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Button]])
LSM:Register('statusbar', 'Cloud Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Cloud]])
LSM:Register('statusbar', 'Comet Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Comet]])
LSM:Register('statusbar', 'Dabs Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Dabs]])
LSM:Register('statusbar', 'ElvUI Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\ElvUI]])
LSM:Register('statusbar', 'Falumn Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Falumn]])
LSM:Register('statusbar', 'Flat Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Flat]])
LSM:Register('statusbar', 'Frost Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Frost]])
LSM:Register('statusbar', 'Glamour Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour]])
LSM:Register('statusbar', 'Glamour2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour2]])
LSM:Register('statusbar', 'Glamour3 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour3]])
LSM:Register('statusbar', 'Glamour4 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour4]])
LSM:Register('statusbar', 'Glamour5 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour5]])
LSM:Register('statusbar', 'Glamour6 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour6]])
LSM:Register('statusbar', 'Glamour7 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour7]])
LSM:Register('statusbar', 'Glaze Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze]])
LSM:Register('statusbar', 'Glaze2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze2]])
LSM:Register('statusbar', 'Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Gloss]])
LSM:Register('statusbar', 'Healbot Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Healbot]])
LSM:Register('statusbar', 'LiteStep Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\LiteStep]])
LSM:Register('statusbar', 'Lyfe Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Lyfe]])
LSM:Register('statusbar', 'Minimalist Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Minimalist]])
LSM:Register('statusbar', 'Otravi Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Otravi]])
LSM:Register('statusbar', 'Outline Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Outline]])
LSM:Register('statusbar', 'Perl Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Perl]])
LSM:Register('statusbar', 'Rocks Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Rocks]])
LSM:Register('statusbar', 'Round Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Round]])
LSM:Register('statusbar', 'Ruben Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Ruben]])
LSM:Register('statusbar', 'Runes Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Runes]])
LSM:Register('statusbar', 'Sinaris Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Sinaris]])
LSM:Register('statusbar', 'Slate Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Slate]])
LSM:Register('statusbar', 'Smooth Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Smooth]])
LSM:Register('statusbar', 'Tukui Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Tukui]])
LSM:Register('statusbar', 'Water Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Water]])

LSM:Register('font', 'Big Noodle Titling', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Dajova', [[Interface\AddOns\DSM\Media\Fonts\Dajova.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Bold', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Light', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Regular', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Saarland', [[Interface\AddOns\DSM\Media\Fonts\Saarland.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Samson', [[Interface\AddOns\DSM\Media\Fonts\Samson.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Sony Sketch', [[Interface\AddOns\DSM\Media\Fonts\SonySketch.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'PT Sans Narrow Bold', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Diediedie', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Visitor TT2 BRK', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Homespun TT BRK', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Action Man', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Continuum Medium', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Arial', [[Interface\AddOns\DSM\Media\Fonts\Arial.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'KGSmallTownSouthernGirl', [[Interface\AddOns\DSM\Media\Fonts\KGSmallTownSouthernGirl.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Youthanasia Texture', [[Interface\AddOns\DSM\Media\Fonts\YOUTHAN.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Youthanasia Texture Regular', [[Interface\AddOns\DSM\Media\Fonts\YOUTTX.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Good Time', [[Interface\AddOns\DSM\Media\Fonts\GOODTIME.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Reprise Title', [[Interface\AddOns\DSM\Media\Fonts\Reprise Title.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Futurapress', [[Interface\AddOns\DSM\Media\Fonts\Futurapress.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Event Horizon', [[Interface\AddOns\DSM\Media\Fonts\Event Horizon.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'H.H. Samuel', [[Interface\AddOns\DSM\Media\Fonts\H.H. Samuel.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Jacinto Sans', [[Interface\AddOns\DSM\Media\Fonts\Jacinto Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'JUSTICE LEAGUE', [[Interface\AddOns\DSM\Media\Fonts\JUSTICE LEAGUE.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'SF Laundromatic Condensed', [[Interface\AddOns\DSM\Media\Fonts\SF Laundromatic Condensed.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Skipper Stencil', [[Interface\AddOns\DSM\Media\Fonts\skipper_stencil.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ardnas', [[Interface\AddOns\DSM\Media\Fonts\Ardnas.otf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Impacted', [[Interface\AddOns\DSM\Media\Fonts\Impacted.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Lemondrop', [[Interface\AddOns\DSM\Media\Fonts\Lemondrop.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Mobile Sans', [[Interface\AddOns\DSM\Media\Fonts\Mobile Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Quimbie', [[Interface\AddOns\DSM\Media\Fonts\Quimbie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Monserga Regular', [[Interface\AddOns\DSM\Media\Fonts\Monserga-regular-FFP.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Indulta SemiSerif', [[Interface\AddOns\DSM\Media\Fonts\Indulta-SemiSerif-boldFFP.otf]])
LSM:Register('font', 'CLUB', [[Interface\AddOns\DSM\Media\Fonts\CLUB____.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Adigiana Ultra', [[Interface\AddOns\DSM\Media\Fonts\Adigiana Ultra.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tabarra Shadow', [[Interface\AddOns\DSM\Media\Fonts\Tabarra-Shadow-FFP.otf]])
LSM:Register('font', 'Sturkopf', [[Interface\AddOns\DSM\Media\Fonts\Sturkopf.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Bold', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Light', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Medium', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Medium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Zektonbo', [[Interface\AddOns\DSM\Media\Fonts\zektonbo.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Aron Grotesque Bold', [[Interface\AddOns\DSM\Media\Fonts\aron_grotesque_bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'AIdealist Sans', [[Interface\AddOns\DSM\Media\Fonts\Idealist Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Sarpanch SemiBold', [[Interface\AddOns\DSM\Media\Fonts\Sarpanch-SemiBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Semi Casual', [[Interface\AddOns\DSM\Media\Fonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'futurademic', [[Interface\CustomFonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Bold', [[Interface\CustomFonts\OpenSans-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-BoldItalic', [[Interface\CustomFonts\OpenSans-BoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-ExtraBold', [[Interface\CustomFonts\OpenSans-ExtraBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-ExtraBoldItalic', [[Interface\CustomFonts\OpenSans-ExtraBoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Italic', [[Interface\CustomFonts\OpenSans-Italic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Light', [[Interface\CustomFonts\OpenSans-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-LightItalic', [[Interface\CustomFonts\OpenSans-LightItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Regular', [[Interface\CustomFonts\OpenSans-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Semibold', [[Interface\CustomFonts\OpenSans-Semibold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-SemiboldItalic', [[Interface\CustomFonts\OpenSans-SemiboldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Supermolot', [[Interface\AddOns\DSM\Media\Fonts\Supermolot.otf]])

LSM:Register('sound', 'Warning', [[Interface\AddOns\DSM\Media\Media\Sounds\Warning.mp3]])

LSM:Register('font', 'Tukui Pixel', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tukui Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tukui UnitFrame', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)

if not select(4, GetAddOnInfo('ElvUI')) then
	LSM:Register('font', 'ElvUI Alt-Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Alt-Font', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Combat', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Font', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Pixel', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('statusbar', 'ElvUI Gloss', [[Interface\AddOns\DSM\Media\StatusBars\ElvUI]])
end